# Generated by Django 6.0.6 on 2026-07-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('job_seeker', 'Job Seeker')], default='job_seeker', max_length=20),
        ),
    ]
