# Generated by Django 6.0.6 on 2026-07-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('job_seeker', 'job_seeker')], default='job_seeker', max_length=20),
        ),
    ]
